# -*- coding: utf-8 -*-
"""Bangla_Smishing_Detection_Hybrid_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d_BMOYGgnrM9Yy0Qy-gdFmlduO7XlHDE
"""

# ============================================================
# 🔒 SMS Phishing & Spam Detector — FULLY FIXED v3
# XLM-RoBERTa + BanglaBERT + URL Analysis + Google Safe Browsing
# Google Colab Ready ✅ | PyTorch 2.6 Compatible ✅
# ============================================================

# ──────────────────────────────────────────────
# CELL 1 — Install Dependencies
# ──────────────────────────────────────────────
# !pip install transformers torch scikit-learn pandas numpy tqdm matplotlib seaborn requests


# ──────────────────────────────────────────────
# CELL 2 — Imports
# ──────────────────────────────────────────────
import os
import re
import random
import requests
import numpy as np
import pandas as pd
import torch
import torch.nn as nn
import torch.serialization
import matplotlib.pyplot as plt
import seaborn as sns

from urllib.parse import urlparse
from torch.utils.data import Dataset, DataLoader
from transformers import AutoTokenizer, AutoModel
from torch.optim import AdamW
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    accuracy_score, classification_report,
    roc_auc_score, confusion_matrix, roc_curve
)
from tqdm import tqdm

print("✅ All libraries imported successfully!")


# ──────────────────────────────────────────────
# CELL 3 — Configuration
# ──────────────────────────────────────────────
CONFIG = {
    "data_path":        os.getenv("DATA_PATH", "data/combined_SMS_Spam_and_Ham_dataset.csv"),
    "model_save_path":  os.getenv("MODEL_SAVE_PATH", "models/best_model.pt"),
    "max_length":       256,
    "batch_size":       8,
    "epochs":           5,
    "learning_rate":    1e-5,
    "test_size":        0.2,
    "random_seed":      42,

    # API keys are read from environment variables. Never hard-code secrets.
    "google_safebrowsing_key": os.getenv("GOOGLE_SAFE_BROWSING_KEY", ""),
    "virustotal_key":          os.getenv("VIRUSTOTAL_API_KEY", "")
}

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"✅ Device: {DEVICE}")
torch.manual_seed(CONFIG["random_seed"])
np.random.seed(CONFIG["random_seed"])


# ──────────────────────────────────────────────
# CELL 4 — URL Patterns & Keywords
# ──────────────────────────────────────────────
URL_PATTERN = re.compile(
    r'(https?://[^\s]+|www\.[^\s]+|'
    r'[a-zA-Z0-9\-]+\.(com|net|org|bd|info|xyz|ru|tk|ml|ga|cf|gq|'
    r'click|link|ly|online|site|top|win|buzz)[^\s]*)',
    re.IGNORECASE
)

SUSPICIOUS_KEYWORDS = [
    'login', 'verify', 'account', 'secure', 'update', 'banking',
    'free', 'prize', 'winner', 'click', 'confirm', 'urgent',
    'password', 'credit', 'debit', 'otp', 'pin', 'kyc',
    'bkash', 'nagad', 'rocket', 'dutch-bangla', 'islami',
]

SHORT_URL_DOMAINS = [
    'bit.ly', 'tinyurl', 't.co', 'goo.gl', 'ow.ly',
    'short.link', 'rebrand.ly', 'cutt.ly',
]

SUSPICIOUS_TLDS = [
    '.ru', '.tk', '.ml', '.ga', '.cf', '.xyz',
    '.click', '.top', '.win', '.buzz', '.online',
]

BRAND_NAMES = [
    'paypal', 'amazon', 'google', 'facebook', 'apple',
    'microsoft', 'bank', 'bkash', 'nagad', 'dutch-bangla',
    'dbbl', 'islami', 'ucb', 'brac', 'sonali',
]

print("✅ URL patterns & keywords configured!")


# ──────────────────────────────────────────────
# CELL 5 — URL Feature Extraction
# ──────────────────────────────────────────────
def analyze_url(url):
    features = {
        'domain_length':        0,
        'subdomain_count':      0,
        'has_digits_in_domain': 0,
        'is_https':             0,
        'suspicious_tld':       0,
        'brand_impersonation':  0,
        'has_at_symbol':        0,
        'has_ip':               0,
        'suspicious_path':      0,
        'is_short_url':         0,
        'path_length':          0,
        'query_length':         0,
        'special_char_count':   0,
    }
    try:
        parsed = urlparse(url)
        domain = parsed.netloc.lower()
        path   = parsed.path.lower()
        query  = parsed.query.lower()

        features['domain_length']        = len(domain)
        features['subdomain_count']      = max(0, domain.count('.') - 1)
        features['has_digits_in_domain'] = int(any(c.isdigit() for c in domain))
        features['is_https']             = int(parsed.scheme == 'https')
        features['suspicious_tld']       = int(any(domain.endswith(t) for t in SUSPICIOUS_TLDS))
        features['brand_impersonation']  = int(any(b in domain for b in BRAND_NAMES))
        features['has_at_symbol']        = int('@' in url)
        features['has_ip']               = int(bool(re.match(r'\d+\.\d+\.\d+\.\d+', domain)))
        features['suspicious_path']      = int(any(kw in path for kw in SUSPICIOUS_KEYWORDS))
        features['is_short_url']         = int(any(s in domain for s in SHORT_URL_DOMAINS))
        features['path_length']          = len(path)
        features['query_length']         = len(query)
        features['special_char_count']   = len(re.findall(r'[%\-_=&?]', url))
    except Exception:
        pass
    return features


def get_url_risk_score(url_features):
    score = (
        url_features.get('suspicious_tld',      0) * 2.0 +
        url_features.get('brand_impersonation',  0) * 3.0 +
        url_features.get('has_ip',               0) * 3.0 +
        url_features.get('has_at_symbol',        0) * 2.5 +
        url_features.get('suspicious_path',      0) * 1.5 +
        url_features.get('is_short_url',         0) * 1.0 +
        url_features.get('has_digits_in_domain', 0) * 0.5 +
        min(url_features.get('subdomain_count',  0) * 0.5, 2.0)
    )
    return min(score, 10.0)


def extract_sms_url_features(text):
    urls        = URL_PATTERN.findall(str(text))
    url_strings = [u[0] if isinstance(u, tuple) else u for u in urls]

    if not url_strings:
        return {
            'has_url': 0, 'url_count': 0, 'max_url_risk': 0.0,
            'has_short_url': 0, 'has_suspicious_url': 0,
            'has_ip_url': 0, 'has_brand_impersonation': 0,
            'total_url_special_chars': 0,
        }

    all_features = [analyze_url(u) for u in url_strings]
    risk_scores  = [get_url_risk_score(f) for f in all_features]

    return {
        'has_url':                 1,
        'url_count':               len(url_strings),
        'max_url_risk':            float(max(risk_scores)),
        'has_short_url':           int(any(f['is_short_url']        for f in all_features)),
        'has_suspicious_url':      int(any(f['suspicious_path']     for f in all_features)),
        'has_ip_url':              int(any(f['has_ip']              for f in all_features)),
        'has_brand_impersonation': int(any(f['brand_impersonation'] for f in all_features)),
        'total_url_special_chars': int(sum(f['special_char_count']  for f in all_features)),
    }

print("✅ URL feature extractor ready!")


# ──────────────────────────────────────────────
# CELL 6 — Real-time URL Threat APIs
# ──────────────────────────────────────────────
def check_google_safe_browsing(urls, api_key):
    if not api_key:
        return {}
    payload = {
        "client":     {"clientId": "sms-phishing-detector", "clientVersion": "1.0"},
        "threatInfo": {
            "threatTypes":      ["MALWARE", "SOCIAL_ENGINEERING",
                                 "UNWANTED_SOFTWARE", "POTENTIALLY_HARMFUL_APPLICATION"],
            "platformTypes":    ["ANY_PLATFORM"],
            "threatEntryTypes": ["URL"],
            "threatEntries":    [{"url": u} for u in urls],
        }
    }
    try:
        resp    = requests.post(
            f"https://safebrowsing.googleapis.com/v4/threatMatches:find?key={api_key}",
            json=payload, timeout=10
        )
        data    = resp.json()
        matches = data.get('matches', [])
        result  = {u: {'is_dangerous': False, 'threat_type': 'SAFE'} for u in urls}
        for m in matches:
            url = m['threat']['url']
            if url in result:
                result[url] = {
                    'is_dangerous': True,
                    'threat_type':  m.get('threatType', 'UNKNOWN'),
                }
        return result
    except Exception as e:
        print(f"⚠️ Google Safe Browsing error: {e}")
        return {}


def check_virustotal(url, api_key):
    if not api_key:
        return {'is_phishing': False, 'malicious_count': 0, 'total_engines': 0}
    try:
        headers = {"x-apikey": api_key}
        r1      = requests.post(
            "https://www.virustotal.com/api/v3/urls",
            headers=headers, data={"url": url}, timeout=15
        )
        scan_id = r1.json()['data']['id']
        r2      = requests.get(
            f"https://www.virustotal.com/api/v3/analyses/{scan_id}",
            headers=headers, timeout=15
        )
        stats = r2.json()['data']['attributes']['stats']
        mal   = stats.get('malicious', 0)
        total = sum(stats.values())
        return {'is_phishing': mal > 3, 'malicious_count': mal, 'total_engines': total}
    except Exception as e:
        print(f"⚠️ VirusTotal error: {e}")
        return {'is_phishing': False, 'malicious_count': 0, 'total_engines': 0}

print("✅ Real-time API functions ready!")


# ──────────────────────────────────────────────
# CELL 7 — Data Loading & Preprocessing
# ──────────────────────────────────────────────
def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'https?://[^\s]+', ' [URL] ', text)
    text = re.sub(r'www\.[^\s]+',     ' [URL] ', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text


def add_text_features(df):
    df['len']         = df['text'].apply(len)
    df['word_count']  = df['text'].apply(lambda x: len(x.split()))
    df['digits']      = df['text'].apply(lambda x: sum(c.isdigit() for c in x))
    df['special']     = df['text'].apply(lambda x: len(re.findall(r'[!@#\$%\^&\*]', x)))
    df['upper_ratio'] = df['text_raw'].apply(
        lambda x: sum(c.isupper() for c in str(x)) / max(len(str(x)), 1)
    )
    return df


def load_and_preprocess(path):
    print("📂 Loading dataset...")
    df = pd.read_csv(path)

    # ── FIX 1: প্রথমেই NaN drop ──
    df = df.dropna(subset=['text', 'label'])
    df = df.reset_index(drop=True)

    # Normalize labels
    df['label'] = df['label'].astype(str).str.lower().str.strip()
    df = df[~df['label'].isin(['promo', 'promotion', 'promotional'])]
    df['label'] = df['label'].replace({
        'smish':    'spam', 'smishing': 'spam',
        'phishing': 'spam', 'fraud':    'spam',
        'normal':   'ham',
    })
    df = df[df['label'].isin(['spam', 'ham'])].copy()
    df = df.reset_index(drop=True)

    # Raw text
    df['text_raw'] = df['text'].copy()
    df['text']     = df['text'].apply(clean_text)
    df.drop_duplicates(subset=['text'], inplace=True)
    df = df.reset_index(drop=True)

    # ── FIX 2: target সঠিকভাবে তৈরি ──
    df['target'] = df['label'].map({'spam': 1, 'ham': 0})
    df = df.dropna(subset=['target'])
    df['target'] = df['target'].astype(int)

    # Text features
    df = add_text_features(df)

    # URL features
    print("🔗 Extracting URL features (একটু সময় লাগবে)...")
    url_feat_df = df['text_raw'].apply(
        lambda x: pd.Series(extract_sms_url_features(x))
    )
    df = pd.concat([df.reset_index(drop=True), url_feat_df], axis=1)

    # ── FIX 3: সব NaN fill ──
    df = df.fillna(0)
    df = df.reset_index(drop=True)

    print(f"✅ Dataset loaded: {len(df)} samples | "
          f"Spam: {df['target'].sum()} | Ham: {(df['target']==0).sum()}")
    return df


df = load_and_preprocess(CONFIG["data_path"])

# Final NaN check
print("\n🔍 NaN check:")
print(df[['text', 'label', 'target']].isnull().sum())
print(f"target dtype: {df['target'].dtype}")


# ──────────────────────────────────────────────
# CELL 8 — Meta Feature Columns
# ──────────────────────────────────────────────
META_COLS = [
    'len', 'word_count', 'digits', 'special', 'upper_ratio',
    'has_url', 'url_count', 'max_url_risk',
    'has_short_url', 'has_suspicious_url',
    'has_ip_url', 'has_brand_impersonation', 'total_url_special_chars',
]
META_DIM = len(META_COLS)

df[META_COLS] = df[META_COLS].fillna(0)
print(f"✅ Meta features ({META_DIM}): {META_COLS}")


# ──────────────────────────────────────────────
# CELL 9 — Train/Test Split
# ──────────────────────────────────────────────

# ── FIX 4: split এর আগে final safety check ──
df = df.dropna(subset=['target'])
df['target'] = df['target'].astype(int)
df = df.reset_index(drop=True)

print(f"✅ Final dataset: {len(df)} samples")
print(f"Spam: {df['target'].sum()} | Ham: {(df['target']==0).sum()}")
print(f"NaN in target: {df['target'].isnull().sum()}")

train_df, test_df = train_test_split(
    df,
    test_size=CONFIG["test_size"],
    stratify=df['target'],
    random_state=CONFIG["random_seed"]
)
print(f"✅ Train: {len(train_df)} | Test: {len(test_df)}")


# ──────────────────────────────────────────────
# CELL 10 — Tokenizers
# ──────────────────────────────────────────────
print("⏳ Tokenizer load হচ্ছে (প্রথমবার download হবে)...")
tok1 = AutoTokenizer.from_pretrained("xlm-roberta-base")
tok2 = AutoTokenizer.from_pretrained("csebuetnlp/banglabert")
print("✅ Tokenizers loaded!")


# ──────────────────────────────────────────────
# CELL 11 — Dataset Class
# ──────────────────────────────────────────────
class SMSDataset(Dataset):
    def __init__(self, df, max_length=256):
        self.texts   = df['text'].values
        self.labels  = df['target'].values.astype(int)
        self.meta    = df[META_COLS].fillna(0).values.astype(np.float32)
        self.max_len = max_length

    def __len__(self):
        return len(self.labels)

    def __getitem__(self, idx):
        t  = self.texts[idx]
        e1 = tok1(t, padding='max_length', truncation=True,
                  max_length=self.max_len, return_tensors='pt')
        e2 = tok2(t, padding='max_length', truncation=True,
                  max_length=self.max_len, return_tensors='pt')
        return {
            'ids1':  e1['input_ids'].squeeze(),
            'mask1': e1['attention_mask'].squeeze(),
            'ids2':  e2['input_ids'].squeeze(),
            'mask2': e2['attention_mask'].squeeze(),
            'meta':  torch.tensor(self.meta[idx], dtype=torch.float),
            'label': torch.tensor(self.labels[idx], dtype=torch.long),
        }

print("✅ Dataset class ready!")


# ──────────────────────────────────────────────
# CELL 12 — Model Architecture
# ──────────────────────────────────────────────
class PhishingDetector(nn.Module):
    def __init__(self, meta_dim=META_DIM):
        super().__init__()

        self.xlm    = AutoModel.from_pretrained("xlm-roberta-base")
        self.bangla = AutoModel.from_pretrained("csebuetnlp/banglabert")

        self.meta_encoder = nn.Sequential(
            nn.Linear(meta_dim, 64),
            nn.ReLU(),
            nn.Dropout(0.2),
            nn.Linear(64, 64),
            nn.ReLU(),
        )

        self.attn_pool1 = nn.Linear(768, 1)
        self.attn_pool2 = nn.Linear(768, 1)

        fusion_dim = 768 + 768 + 64
        self.classifier = nn.Sequential(
            nn.Linear(fusion_dim, 512),
            nn.GELU(),
            nn.Dropout(0.4),
            nn.Linear(512, 128),
            nn.GELU(),
            nn.Dropout(0.2),
            nn.Linear(128, 2),
        )

    def _weighted_pool(self, hidden, attn_layer):
        weights = torch.softmax(attn_layer(hidden), dim=1)
        return (hidden * weights).sum(dim=1)

    def forward(self, ids1, mask1, ids2, mask2, meta):
        h1 = self.xlm(ids1,    attention_mask=mask1).last_hidden_state
        h2 = self.bangla(ids2, attention_mask=mask2).last_hidden_state
        o1 = self._weighted_pool(h1, self.attn_pool1)
        o2 = self._weighted_pool(h2, self.attn_pool2)
        m  = self.meta_encoder(meta)
        x  = torch.cat([o1, o2, m], dim=1)
        return self.classifier(x)


print("⏳ Model তৈরি হচ্ছে...")
model        = PhishingDetector(meta_dim=META_DIM).to(DEVICE)
total_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"✅ Model ready! Parameters: {total_params:,}")


# ──────────────────────────────────────────────
# CELL 13 — DataLoaders
# ──────────────────────────────────────────────
train_loader = DataLoader(
    SMSDataset(train_df, CONFIG["max_length"]),
    batch_size=CONFIG["batch_size"], shuffle=True,
    num_workers=2, pin_memory=True
)
test_loader = DataLoader(
    SMSDataset(test_df, CONFIG["max_length"]),
    batch_size=CONFIG["batch_size"], shuffle=False,
    num_workers=2, pin_memory=True
)
print(f"✅ Train batches: {len(train_loader)} | Test batches: {len(test_loader)}")


# ──────────────────────────────────────────────
# CELL 14 — Optimizer, Scheduler, Loss
# ──────────────────────────────────────────────
optimizer    = AdamW(model.parameters(), lr=CONFIG["learning_rate"], weight_decay=0.01)
total_steps  = len(train_loader) * CONFIG["epochs"]
scheduler    = torch.optim.lr_scheduler.OneCycleLR(
    optimizer, max_lr=CONFIG["learning_rate"],
    total_steps=total_steps, pct_start=0.1
)

spam_count = int((train_df['target'] == 1).sum())
ham_count  = int((train_df['target'] == 0).sum())
weight     = torch.tensor([1.0, ham_count / spam_count], dtype=torch.float).to(DEVICE)
criterion  = nn.CrossEntropyLoss(weight=weight)

print(f"✅ Optimizer ready! Ham weight: 1.0 | Spam weight: {ham_count/spam_count:.2f}")


# ──────────────────────────────────────────────
# CELL 15 — Training Loop (FIXED torch.save)
# ──────────────────────────────────────────────
def run_epoch(loader, train=True):
    if train:
        model.train()
    else:
        model.eval()

    total_loss, all_probs, all_labels = 0.0, [], []

    ctx = torch.enable_grad() if train else torch.no_grad()
    with ctx:
        for batch in tqdm(loader, desc="Train" if train else "Eval", leave=False):
            ids1   = batch['ids1'].to(DEVICE)
            mask1  = batch['mask1'].to(DEVICE)
            ids2   = batch['ids2'].to(DEVICE)
            mask2  = batch['mask2'].to(DEVICE)
            meta   = batch['meta'].to(DEVICE)
            labels = batch['label'].to(DEVICE)

            logits = model(ids1, mask1, ids2, mask2, meta)
            loss   = criterion(logits, labels)

            if train:
                optimizer.zero_grad()
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
                scheduler.step()

            total_loss += loss.item()
            probs = torch.softmax(logits, dim=1)[:, 1]
            all_probs.extend(probs.detach().cpu().numpy())
            all_labels.extend(labels.cpu().numpy())

    return total_loss / len(loader), np.array(all_probs), np.array(all_labels)


history  = {'train_loss': [], 'val_loss': [], 'val_auc': [], 'val_acc': []}
best_auc = 0.0

print(f"\n🚀 Training শুরু — {CONFIG['epochs']} epochs on {DEVICE}...\n")

for epoch in range(1, CONFIG["epochs"] + 1):
    print(f"{'='*60}")
    print(f"Epoch {epoch}/{CONFIG['epochs']}")

    t_loss, _, _              = run_epoch(train_loader, train=True)
    v_loss, v_probs, v_labels = run_epoch(test_loader,  train=False)

    best_acc, best_thresh = 0.0, 0.5
    for thresh in np.arange(0.2, 0.8, 0.01):
        preds = (v_probs > thresh).astype(int)
        acc   = accuracy_score(v_labels, preds)
        if acc > best_acc:
            best_acc, best_thresh = acc, thresh

    v_auc = roc_auc_score(v_labels, v_probs)

    history['train_loss'].append(t_loss)
    history['val_loss'].append(v_loss)
    history['val_auc'].append(v_auc)
    history['val_acc'].append(best_acc)

    print(f"  Train Loss : {t_loss:.4f}")
    print(f"  Val Loss   : {v_loss:.4f}")
    print(f"  Val AUC    : {v_auc:.4f}")
    print(f"  Val Acc    : {best_acc:.4f}  (threshold={best_thresh:.2f})")

    if v_auc > best_auc:
        best_auc = v_auc

        # ── FIX 5: PyTorch 2.6 compatible save ──
        save_dict = {
            'epoch':     int(epoch),
            'model':     model.state_dict(),
            'optimizer': optimizer.state_dict(),
            'auc':       float(best_auc),
            'threshold': float(best_thresh),
        }
        torch.save(save_dict, CONFIG["model_save_path"])
        print(f"  💾 Best model saved! (AUC={best_auc:.4f})")

print(f"\n✅ Training complete! Best AUC: {best_auc:.4f}")


# ──────────────────────────────────────────────
# CELL 16 — Evaluation & Plots (FIXED torch.load)
# ──────────────────────────────────────────────

# ── FIX 6: PyTorch 2.6 compatible load ──
ckpt = torch.load(
    CONFIG["model_save_path"],
    map_location=DEVICE,
    weights_only=False          # ← এই parameter যোগ করা হয়েছে
)
best_thresh = float(ckpt['threshold'])
model.load_state_dict(ckpt['model'])
print(f"✅ Best model loaded — Epoch {ckpt['epoch']} | AUC={ckpt['auc']:.4f}")

_, final_probs, final_labels = run_epoch(test_loader, train=False)
final_preds = (final_probs > best_thresh).astype(int)

print("\n" + "="*55)
print("📊 FINAL EVALUATION RESULTS")
print("="*55)
print(f"Best Threshold : {best_thresh:.2f}")
print(f"Accuracy       : {accuracy_score(final_labels, final_preds):.4f}")
print(f"ROC-AUC        : {roc_auc_score(final_labels, final_probs):.4f}")
print("\nClassification Report:")
print(classification_report(final_labels, final_preds, target_names=['Ham', 'Spam']))

# ── Plots ──
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
fig.suptitle("SMS Phishing Detector — Training Results", fontsize=16, fontweight='bold')

axes[0, 0].plot(history['train_loss'], label='Train Loss', marker='o')
axes[0, 0].plot(history['val_loss'],   label='Val Loss',   marker='s')
axes[0, 0].set_title('Loss Curve')
axes[0, 0].set_xlabel('Epoch')
axes[0, 0].legend()
axes[0, 0].grid(True, alpha=0.3)

axes[0, 1].plot(history['val_auc'], label='Val AUC', color='green', marker='^')
axes[0, 1].set_title('ROC-AUC per Epoch')
axes[0, 1].set_xlabel('Epoch')
axes[0, 1].set_ylim([0.8, 1.0])
axes[0, 1].legend()
axes[0, 1].grid(True, alpha=0.3)

cm = confusion_matrix(final_labels, final_preds)
sns.heatmap(cm, annot=True, fmt='d', cmap='Blues',
            xticklabels=['Ham', 'Spam'],
            yticklabels=['Ham', 'Spam'], ax=axes[1, 0])
axes[1, 0].set_title('Confusion Matrix')
axes[1, 0].set_ylabel('True Label')
axes[1, 0].set_xlabel('Predicted Label')

fpr, tpr, _ = roc_curve(final_labels, final_probs)
axes[1, 1].plot(fpr, tpr, color='darkorange',
                label=f'ROC (AUC={roc_auc_score(final_labels, final_probs):.4f})')
axes[1, 1].plot([0, 1], [0, 1], 'k--')
axes[1, 1].set_title('ROC Curve')
axes[1, 1].set_xlabel('False Positive Rate')
axes[1, 1].set_ylabel('True Positive Rate')
axes[1, 1].legend()
axes[1, 1].grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig("/content/training_results.png", dpi=150, bbox_inches='tight')
plt.show()
print("📊 Plot saved → /content/training_results.png")


# ──────────────────────────────────────────────
# CELL 17 — Inference Function
# ──────────────────────────────────────────────
def predict_sms(text, threshold=None, verbose=True):
    if threshold is None:
        threshold = best_thresh

    model.eval()
    reasons = []

    # Step 1: ML model
    clean     = clean_text(text)
    url_feats = extract_sms_url_features(text)

    meta_vals = np.array([[
        len(clean),
        len(clean.split()),
        sum(c.isdigit() for c in clean),
        len(re.findall(r'[!@#\$%\^&\*]', clean)),
        sum(c.isupper() for c in text) / max(len(text), 1),
        url_feats['has_url'],
        url_feats['url_count'],
        url_feats['max_url_risk'],
        url_feats['has_short_url'],
        url_feats['has_suspicious_url'],
        url_feats['has_ip_url'],
        url_feats['has_brand_impersonation'],
        url_feats['total_url_special_chars'],
    ]], dtype=np.float32)

    e1 = tok1(clean, padding='max_length', truncation=True,
              max_length=CONFIG["max_length"], return_tensors='pt')
    e2 = tok2(clean, padding='max_length', truncation=True,
              max_length=CONFIG["max_length"], return_tensors='pt')

    with torch.no_grad():
        logits = model(
            e1['input_ids'].to(DEVICE),
            e1['attention_mask'].to(DEVICE),
            e2['input_ids'].to(DEVICE),
            e2['attention_mask'].to(DEVICE),
            torch.tensor(meta_vals).to(DEVICE),
        )
        prob = torch.softmax(logits, dim=1)[0, 1].item()

    if prob > threshold:
        reasons.append(f"ML model confidence: {prob:.1%}")

    # Step 2: URL analysis
    urls        = URL_PATTERN.findall(text)
    url_strings = [u[0] if isinstance(u, tuple) else u for u in urls]
    url_details = []

    for url in url_strings:
        feats = analyze_url(url)
        risk  = get_url_risk_score(feats)
        url_details.append({'url': url, 'risk': risk, 'features': feats})

        if feats['brand_impersonation']:
            reasons.append(f"⚠️  Brand impersonation in URL: {url}")
        if feats['has_ip']:
            reasons.append(f"⚠️  IP-address URL: {url}")
        if feats['is_short_url']:
            reasons.append(f"⚠️  Shortened URL: {url}")
        if feats['suspicious_tld']:
            reasons.append(f"⚠️  Suspicious domain extension: {url}")
        if feats['suspicious_path']:
            reasons.append(f"⚠️  Suspicious path keywords: {url}")
        if feats['has_at_symbol']:
            reasons.append(f"⚠️  @ symbol in URL (phishing trick): {url}")

    # Step 3: Google Safe Browsing
    gsb_results = {}
    if url_strings and CONFIG["google_safebrowsing_key"]:
        gsb_results = check_google_safe_browsing(
            url_strings, CONFIG["google_safebrowsing_key"]
        )
        for url, res in gsb_results.items():
            if res['is_dangerous']:
                reasons.append(
                    f"🚨 Google Safe Browsing [{res['threat_type']}]: {url}"
                )

    # Step 4: VirusTotal
    vt_results = {}
    if url_strings and CONFIG["virustotal_key"]:
        for url in url_strings[:2]:
            vt = check_virustotal(url, CONFIG["virustotal_key"])
            vt_results[url] = vt
            if vt['is_phishing']:
                reasons.append(
                    f"🚨 VirusTotal: {vt['malicious_count']}/{vt['total_engines']} "
                    f"flagged: {url}"
                )

    is_phishing = (prob > threshold) or bool(reasons)
    verdict     = "🚨 PHISHING / SPAM" if is_phishing else "✅ SAFE (HAM)"

    result = {
        'verdict':     verdict,
        'ml_prob':     prob,
        'threshold':   threshold,
        'is_phishing': is_phishing,
        'reasons':     reasons,
        'urls_found':  url_strings,
        'url_details': url_details,
        'gsb_results': gsb_results,
        'vt_results':  vt_results,
    }

    if verbose:
        print("\n" + "="*60)
        print("🔍 SMS PHISHING ANALYSIS REPORT")
        print("="*60)
        print(f"📱 SMS      : {text[:120]}{'...' if len(text) > 120 else ''}")
        print(f"🤖 ML Score : {prob:.1%}  (threshold={threshold:.2f})")
        print(f"🔗 URLs     : {len(url_strings)} found → {url_strings}")
        print(f"\n📋 VERDICT  : {verdict}")
        if reasons:
            print("\n⚠️  Reasons:")
            for r in reasons:
                print(f"   • {r}")
        if url_details:
            print("\n🔗 URL Risk Scores:")
            for d in url_details:
                print(f"   [{d['risk']:.1f}/10] {d['url']}")
        print("="*60)

    return result


# ──────────────────────────────────────────────
# CELL 18 — Test Examples
# ──────────────────────────────────────────────
test_messages = [
    # Phishing
    "Congratulations! You won BDT 50,000. Verify now: http://bd-prize.xyz/claim/winner",
    "URGENT: Your bKash account is suspended. Login: http://192.168.1.1/bkash/verify",
    "Free gift! Click: http://bit.ly/3xWin99 to claim your prize immediately!",
    "Your bank account will be closed. Update KYC: http://dbbl-secure.ru/login",
    # Safe
    "Tomar parcel ajtke deliver hobe. Track: https://pathao.com/track/ABC123",
    "Mom, I will be home by 8pm. Don't worry!",
    "Your OTP is 482910. Do not share with anyone. Valid for 5 minutes.",
]

print("\n🧪 Example SMS test হচ্ছে...\n")
for msg in test_messages:
    predict_sms(msg, verbose=True)


# ──────────────────────────────────────────────
# CELL 19 — Interactive Widget (Colab)
# ──────────────────────────────────────────────
from IPython.display import display
import ipywidgets as widgets

txt_input = widgets.Textarea(
    placeholder='যেকোনো SMS এখানে paste করুন...',
    layout=widgets.Layout(width='80%', height='80px')
)
btn = widgets.Button(description="🔍 Analyze SMS", button_style='danger')
out = widgets.Output()


def on_click(b):
    out.clear_output()
    with out:
        if txt_input.value.strip():
            predict_sms(txt_input.value, verbose=True)
        else:
            print("⚠️ কোনো SMS লেখা নেই!")


btn.on_click(on_click)

display(widgets.VBox([
    widgets.HTML("<h3>📱 SMS Phishing Detector</h3>"),
    widgets.Label("SMS টি নিচে paste করুন:"),
    txt_input,
    btn,
    out,
]))

print("\n✅ সব কিছু প্রস্তুত! Widget এ SMS paste করে Analyze করুন।")

# =========================================================
# FIGURE 1 — Dataset Class Distribution
# =========================================================

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(6,5))

ax = sns.countplot(
    x='label',
    data=df,
    palette='Set2'
)

plt.title(
    "Dataset Class Distribution",
    fontsize=16,
    fontweight='bold'
)

plt.xlabel("Class", fontsize=13)
plt.ylabel("Number of Samples", fontsize=13)

# value show
for p in ax.patches:
    ax.annotate(
        f'{int(p.get_height())}',
        (p.get_x() + p.get_width()/2., p.get_height()),
        ha='center',
        va='bottom',
        fontsize=12
    )

plt.grid(axis='y', linestyle='--', alpha=0.3)

plt.tight_layout()

plt.savefig(
    "results/class_distribution.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

print("✅ Saved: class_distribution.png")

# =========================================================
# FIGURE 2 — Pie Chart
# =========================================================

labels = df['label'].value_counts().index
sizes  = df['label'].value_counts().values

plt.figure(figsize=(6,6))

plt.pie(
    sizes,
    labels=labels,
    autopct='%1.1f%%',
    startangle=90,
    shadow=True
)

plt.title(
    "Spam vs Ham Percentage",
    fontsize=16,
    fontweight='bold'
)

plt.tight_layout()

plt.savefig(
    "results/pie_distribution.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

print("✅ Saved: pie_distribution.png")

# =========================================================
# FIGURE 3 — SMS Length Distribution
# =========================================================

plt.figure(figsize=(8,5))

sns.histplot(
    data=df,
    x='len',
    hue='label',
    bins=50,
    kde=True
)

plt.title(
    "SMS Length Distribution",
    fontsize=16,
    fontweight='bold'
)

plt.xlabel("SMS Length")
plt.ylabel("Frequency")

plt.tight_layout()

plt.savefig(
    "results/sms_length_distribution.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

print("✅ Saved: sms_length_distribution.png")

# =========================================================
# FIGURE 4 — URL Feature Analysis
# =========================================================

url_features = [
    'has_url',
    'has_short_url',
    'has_suspicious_url',
    'has_ip_url',
    'has_brand_impersonation'
]

values = [df[col].sum() for col in url_features]

plt.figure(figsize=(8,5))

bars = plt.bar(url_features, values)

plt.title(
    "URL-based Phishing Features",
    fontsize=16,
    fontweight='bold'
)

plt.ylabel("Count")

plt.xticks(rotation=15)

for bar in bars:
    height = bar.get_height()
    plt.text(
        bar.get_x() + bar.get_width()/2,
        height,
        f'{int(height)}',
        ha='center',
        va='bottom'
    )

plt.tight_layout()

plt.savefig(
    "results/url_feature_analysis.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

print("✅ Saved: url_feature_analysis.png")

# =========================================================
# FIGURE 5 — Training vs Validation Loss
# =========================================================

plt.figure(figsize=(7,5))

plt.plot(
    history['train_loss'],
    marker='o',
    linewidth=2,
    label='Train Loss'
)

plt.plot(
    history['val_loss'],
    marker='s',
    linewidth=2,
    label='Validation Loss'
)

plt.title(
    "Training vs Validation Loss",
    fontsize=16,
    fontweight='bold'
)

plt.xlabel("Epoch")
plt.ylabel("Loss")

plt.legend()

plt.grid(True, alpha=0.3)

plt.tight_layout()

plt.savefig(
    "results/loss_curve.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

print("✅ Saved: loss_curve.png")

# =========================================================
# FIGURE 6 — ROC Curve
# =========================================================

from sklearn.metrics import roc_curve, roc_auc_score

fpr, tpr, _ = roc_curve(final_labels, final_probs)

auc_score = roc_auc_score(final_labels, final_probs)

plt.figure(figsize=(6,6))

plt.plot(
    fpr,
    tpr,
    linewidth=2,
    label=f'AUC = {auc_score:.4f}'
)

plt.plot([0,1], [0,1], linestyle='--')

plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")

plt.title(
    "ROC Curve",
    fontsize=16,
    fontweight='bold'
)

plt.legend()

plt.grid(True, alpha=0.3)

plt.tight_layout()

plt.savefig(
    "results/roc_curve.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

print("✅ Saved: roc_curve.png")

# =========================================================
# FIGURE 7 — Confusion Matrix
# =========================================================

from sklearn.metrics import confusion_matrix

cm = confusion_matrix(final_labels, final_preds)

plt.figure(figsize=(6,5))

sns.heatmap(
    cm,
    annot=True,
    fmt='d',
    cmap='Blues',
    xticklabels=['Ham', 'Spam'],
    yticklabels=['Ham', 'Spam']
)

plt.title(
    "Confusion Matrix",
    fontsize=16,
    fontweight='bold'
)

plt.xlabel("Predicted")
plt.ylabel("Actual")

plt.tight_layout()

plt.savefig(
    "results/confusion_matrix.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

print("✅ Saved: confusion_matrix.png")

# =========================================================
# FIGURE 8 — Precision Recall F1
# =========================================================

from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(final_labels, final_preds)
recall    = recall_score(final_labels, final_preds)
f1        = f1_score(final_labels, final_preds)

metrics = ['Precision', 'Recall', 'F1-Score']
scores  = [precision, recall, f1]

plt.figure(figsize=(6,5))

bars = plt.bar(metrics, scores)

plt.ylim(0,1)

plt.title(
    "Evaluation Metrics",
    fontsize=16,
    fontweight='bold'
)

for bar in bars:
    h = bar.get_height()
    plt.text(
        bar.get_x()+bar.get_width()/2,
        h,
        f'{h:.3f}',
        ha='center',
        va='bottom'
    )

plt.tight_layout()

plt.savefig(
    "results/evaluation_metrics.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

print("✅ Saved: evaluation_metrics.png")

# =========================================================
# FIGURE 9 — HYBRID MODEL ARCHITECTURE DIAGRAM
# =========================================================

from graphviz import Digraph

dot = Digraph(
    comment='Hybrid SMS Phishing Detection Architecture'
)

dot.attr(rankdir='LR')
dot.attr(fontsize='20')

# Nodes
dot.node('A', 'Input SMS\n(Bangla/English)', shape='box', style='filled')

dot.node('B', 'Text Cleaning\n& Preprocessing', shape='box')

dot.node('C', 'XLM-RoBERTa', shape='box', style='filled')
dot.node('D', 'BanglaBERT', shape='box', style='filled')

dot.node('E', 'Attention Pooling', shape='ellipse')
dot.node('F', 'Attention Pooling', shape='ellipse')

dot.node('G', 'Meta Feature Extraction\n(URL + Text Features)', shape='box')

dot.node('H', 'Feature Fusion', shape='diamond')

dot.node('I', 'Deep Neural Classifier', shape='box', style='filled')

dot.node('J', 'Spam / Ham\nPrediction', shape='box', style='filled')

# Connections
dot.edge('A', 'B')

dot.edge('B', 'C')
dot.edge('B', 'D')
dot.edge('B', 'G')

dot.edge('C', 'E')
dot.edge('D', 'F')

dot.edge('E', 'H')
dot.edge('F', 'H')
dot.edge('G', 'H')

dot.edge('H', 'I')
dot.edge('I', 'J')

# Save
dot.render(
    '/content/hybrid_model_architecture',
    format='png',
    cleanup=True
)

print("✅ Saved: hybrid_model_architecture.png")

!pip install wordcloud

# =========================================================
# FIGURE 10 — SPAM WORD CLOUD
# =========================================================

from wordcloud import WordCloud

spam_text = " ".join(
    df[df['label'] == 'spam']['text'].astype(str)
)

wordcloud = WordCloud(
    width=1200,
    height=600,
    background_color='white',
    collocations=False
).generate(spam_text)

plt.figure(figsize=(12,6))

plt.imshow(wordcloud, interpolation='bilinear')

plt.axis('off')

plt.title(
    "Spam SMS Word Cloud",
    fontsize=18,
    fontweight='bold'
)

plt.tight_layout()

plt.savefig(
    "results/spam_wordcloud.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

print("✅ Saved: spam_wordcloud.png")

# =========================================================
# FIGURE 11 — THRESHOLD OPTIMIZATION
# =========================================================

thresholds = []
accuracies = []

for thresh in np.arange(0.2, 0.8, 0.01):

    preds = (final_probs > thresh).astype(int)

    acc = accuracy_score(final_labels, preds)

    thresholds.append(thresh)
    accuracies.append(acc)

best_idx = np.argmax(accuracies)

plt.figure(figsize=(8,5))

plt.plot(
    thresholds,
    accuracies,
    linewidth=2
)

plt.scatter(
    thresholds[best_idx],
    accuracies[best_idx],
    s=120
)

plt.xlabel("Threshold")
plt.ylabel("Accuracy")

plt.title(
    "Threshold Optimization Curve",
    fontsize=16,
    fontweight='bold'
)

plt.grid(True, alpha=0.3)

plt.tight_layout()

plt.savefig(
    "results/threshold_optimization.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

print("✅ Saved: threshold_optimization.png")

# =========================================================
# FIGURE 12 — FEATURE CORRELATION HEATMAP
# =========================================================

corr = df[META_COLS + ['target']].corr()

plt.figure(figsize=(12,10))

sns.heatmap(
    corr,
    cmap='coolwarm',
    annot=True,
    fmt='.2f'
)

plt.title(
    "Feature Correlation Heatmap",
    fontsize=16,
    fontweight='bold'
)

plt.tight_layout()

plt.savefig(
    "results/feature_correlation_heatmap.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

print("✅ Saved: feature_correlation_heatmap.png")

# =========================================================
# FIGURE 13 — URL RISK SCORE DISTRIBUTION
# =========================================================

spam_df = df[df['has_url'] == 1]

plt.figure(figsize=(8,5))

sns.histplot(
    spam_df['max_url_risk'],
    bins=20,
    kde=True
)

plt.title(
    "URL Risk Score Distribution",
    fontsize=16,
    fontweight='bold'
)

plt.xlabel("Risk Score")
plt.ylabel("Frequency")

plt.tight_layout()

plt.savefig(
    "results/url_risk_distribution.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

print("✅ Saved: url_risk_distribution.png")

# =========================================================
# FIGURE 14 — VALIDATION ACCURACY CURVE
# =========================================================

plt.figure(figsize=(7,5))

plt.plot(
    history['val_acc'],
    marker='o',
    linewidth=2,
    label='Validation Accuracy'
)

plt.xlabel("Epoch")
plt.ylabel("Accuracy")

plt.title(
    "Validation Accuracy Curve",
    fontsize=16,
    fontweight='bold'
)

plt.ylim(0.8, 1.0)

plt.grid(True, alpha=0.3)

plt.legend()

plt.tight_layout()

plt.savefig(
    "results/validation_accuracy_curve.png",
    dpi=300,
    bbox_inches='tight'
)

plt.show()

print("✅ Saved: validation_accuracy_curve.png")

# =========================================================
# FIGURE 15 — SYSTEM WORKFLOW DIAGRAM
# =========================================================

from graphviz import Digraph

workflow = Digraph()

workflow.attr(rankdir='TB')

workflow.node('A', 'SMS Input', shape='box')
workflow.node('B', 'Text Cleaning', shape='box')
workflow.node('C', 'URL Extraction', shape='box')
workflow.node('D', 'Feature Extraction', shape='box')
workflow.node('E', 'Transformer Encoding', shape='box')
workflow.node('F', 'Hybrid Fusion', shape='diamond')
workflow.node('G', 'Threat Intelligence APIs', shape='box')
workflow.node('H', 'Spam / Ham Decision', shape='box')

workflow.edge('A', 'B')
workflow.edge('B', 'C')
workflow.edge('B', 'D')
workflow.edge('B', 'E')

workflow.edge('C', 'G')

workflow.edge('D', 'F')
workflow.edge('E', 'F')
workflow.edge('G', 'F')

workflow.edge('F', 'H')

workflow.render(
    '/content/system_workflow',
    format='png',
    cleanup=True
)

print("✅ Saved: system_workflow.png")

